### ISSUE TITLE
GenerateParser up-to-date check broken if targetRoot does not have trailing "/"

### ISSUE THREAD

**Issue by fedork** [JetBrains/gradle-grammar-kit-plugin#10]
since this code simply concats strings:             

def parserFile = project.file("$targetRoot$pathToParser")
outputs.file parserFile
def psiDir = project.file("$targetRoot$pathToPsiRoot")

it only works properly if targetDir has trailing slash, otherwise it mostly works but up-to-date check and purging do not work properly

**Comment by cedricziel** [comment]
Wow. Came here to report generating the lexer doesnt work correctly, but simply removing the trailing slash works flawlessly. This has cost me a bunch of nerves.
