### ISSUE TITLE
Unable to migrate to 2022.3

### ISSUE THREAD

**Issue by hurricup** [JetBrains/gradle-grammar-kit-plugin#113]
Tried to migrate and failed.
https://github.com/Camelcade/Perl5-IDEA/blob/master/plugin/core/build.gradle#L25

Shows 
```
Some problems were found with the configuration of task ':plugin:core:generatePerl5Parser' (type 'GenerateParserTask').
  - In plugin 'org.jetbrains.grammarkit' type 'org.jetbrains.grammarkit.tasks.GenerateParserTask' property 'parserFile' doesn't have a configured value.
```

Tried to add  (btw, feels like it should be a default value)
```
  targetRoot.set('gen')
```
Didn't help, same result. 
Works fine with previous version

**Comment by hfhbd** [comment]
Do you register your own parser tasks? If so, I guess, you have the same problem described in #108. Workaround: Copy the conventions like I did for sqldelight: https://github.com/AlecStrong/Grammar-Kit-Composer/blob/9561355a723a54bb5da18f85b0bfbafb85e67941/src/main/kotlin/com/alecstrong/grammar/kit/composer/GrammarKitComposerPlugin.kt#L52

**Comment by hfhbd** [comment]
Yeah, #108 is fixed.
