### ISSUE TITLE
GenerateLexer up-to-date checks don't work

### ISSUE THREAD

**Issue by stefansjs** [JetBrains/gradle-grammar-kit-plugin#16]
I have written a GenerateLexer task like so:

```groovy
// Create lexer/parser generator tasks
task generateLexer(type: GenerateLexer) {
    source 'src/main/kotlin/com/flatbuffers/plugin/psi/FlatbuffersLexer.flex'

    targetDir 'src/main/gen/com/flatbuffers/plugin/psi'
    targetClass 'FlexLexer'

    purgeOldFiles true
}
```

But when delete the generated class and re-run, it doesn't notice that there is no output, and it reports "UP-TO-DATE" (and then I don't have a lexer and compilation fails)

**Comment by stefansjs** [comment]
I think gradle is getting confused by the input/output annotations. Here's my workaround
```groovy
task generateLexer(type: JavaExec) {
    main 'jflex.Main'
    classpath project.configurations.compileOnly

    def flexFile = 'src/main/kotlin/com/flatbuffers/plugin/psi/FlatbuffersLexer.flex'
    def targetDir = 'src/main/gen/com/flatbuffers/plugin/lexer'

    inputs.file flexFile
    outputs.dir targetDir

    //noinspection GroovyAssignabilityCheck
    args "-d", targetDir, flexFile
}
```

I actually had to update the .flex file to output to a different package, but in the end I needed this so that the generateLexer and generateParser tasks didn't both produce outputs in the same directory

**Comment by hweigel528** [comment]
Also consistently affected by this issue.

I'm not a gradle expert, but I suspect that some of the @Input annotations in GenerateLexer should really be some type of @Output annotation.

At least that's what I gather from reading: https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks

Clients shouldn't need to build custom upToDate logic to make this task work properly, I hope this issue gets resolved

**Comment by hurricup** [comment]
The thing is we have an input - string with setting and output - file specified by this setting. So every property is corretly marked as input and there is a code registering output file: https://github.com/JetBrains/gradle-grammar-kit-plugin/blob/master/src/main/groovy/org/jetbrains/grammarkit/tasks/GenerateLexer.groovy#L24

But probably it's too late afterEvaluate. I'll check this

**Comment by hsz** [comment]
Fixed with the latest release.
