### ISSUE TITLE
Missing 2020.1 tag and release in this repo

### ISSUE THREAD

**Issue by bryant1410** [JetBrains/gradle-grammar-kit-plugin#26]

**Comment by hurricup** [comment]
and why should it be?

**Comment by bryant1410** [comment]
For consistency? AFAIK, there's a tag and release for every version, except for this one :man_shrugging:

**Comment by hurricup** [comment]
Nope. Only when real changes happens. Like update of default GK or JFlex or some adjustments into the plugin's code. Otherwise - plugin version stays as it is. There are no formal releases
