### ISSUE TITLE
WARN: registry accessed but not loaded yet

### ISSUE THREAD

**Issue by ice1000** [JetBrains/gradle-grammar-kit-plugin#30]
I get the following warnings:
```
> Task :generateArendParser
WARN: The registry key 'psi.track.invalidation' accessed, but not loaded yet
WARN: The registry key 'psi.incremental.reparse.depth.limit' accessed, but not loaded yet
BNF_RULE:letExpr: unexpected cardinality OPTIONAL of expr, treating as ATOM
BNF_RULE:lamExpr: unexpected cardinality OPTIONAL of expr, treating as ATOM
BNF_RULE:piExpr: unexpected cardinality OPTIONAL of expr, treating as ATOM
WARN: The registry key 'platform.random.idempotence.check.rate' accessed, but not loaded yet
```

Repo: https://github.com/JetBrains/intellij-arend/tree/eb029f2377cb81d62ec5159f064f383f590bd9b1

**Comment by hurricup** [comment]
This looks like a GK problem, not this plugin. This plugin just runs GK.

**Comment by ice1000** [comment]
Maybe we can transfer this issue to GK

**Comment by hurricup** [comment]
Seems I need some permission to do that. 
@gregsh

**Comment by gregsh** [comment]
> BNF_RULE:letExpr: unexpected cardinality OPTIONAL of expr, treating as ATOM
> BNF_RULE:lamExpr: unexpected cardinality OPTIONAL of expr, treating as ATOM
> BNF_RULE:piExpr: unexpected cardinality OPTIONAL of expr, treating as ATOM

These are GK generator warnings, you can check your grammar whether the generator choices for your [expression grammar](https://github.com/JetBrains/Grammar-Kit/blob/master/HOWTO.md#24-compact-expression-parsing-with-priorities) are correct.

> WARN: The registry key 'psi.track.invalidation' accessed, but not loaded yet
> WARN: The registry key 'psi.incremental.reparse.depth.limit' accessed, but not loaded yet
> WARN: The registry key 'platform.random.idempotence.check.rate' accessed, but not loaded yet

It is IntelliJ platform warnings. They mean nothing. Please ignore them.

**Comment by ice1000** [comment]
> They mean nothing. Please ignore them.

That's what I was asking for, thanks!
