### ISSUE TITLE
Java 8 compatibility

### ISSUE THREAD

**Issue by jplaisted** [JetBrains/gradle-grammar-kit-plugin#32]
I'm trying to create a new plugin for intellij using grammar kit. When I try to build with gradle I get the following error:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/intellij/lang/LanguageBraceMatching has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

With the task defined as

```
task generatePdlParser(type: GenerateParser) {
  source = "${grammarPath}/Pdl.bnf"
  targetRoot = "${generatedGrammarJavaPath}"
  pathToParser = "/${basePackagePath}/parser/Parser.java"
  pathToPsiRoot = "/${basePackagePath}/psi"
  purgeOldFiles = true
}
```

Using grammar kit `2020.2.1` and intellij plugin `0.5.0`.

All I can tell here is that this a Java 8 vs 11 issue. I'm not sure if this means I have to upgrade my entire project to 11 or if it is something locally on my machine I need to fix. Either way, help is appreciated.

**Comment by hurricup** [comment]
Looks like you need to run gradle with Java 11.
FYI: Idea migrated to Java 11, so there is a little sense to stay on 8

**Comment by jplaisted** [comment]
Yeah, that was it, thanks. Forced my Java version to 11 and it builds now. Thanks!

**Comment by megantracy93** [comment]
I am running into the same issue. I have several other projects that rely on java 8 so I'd rather not force my java version to java 11 everywhere. As specified in the gradle docs, is there a way to override the java home for the grammarkit tasks? https://docs.gradle.org/6.7/userguide/toolchains.html#integration_with_tasks_relying_on_a_java_executable_or_java_home Or is there a possibility of releasing an updated plugin here that sets the java version to java 11?

**Comment by hurricup** [comment]
@megantracy93 you may use previous versions of plugin and/or grammar-kit with java 8 support.

**Comment by megantracy93** [comment]
@hurricup I am trying to upgrade my plugin to work against IntelliJ 2020.3 which requires java 11 to work: https://jetbrains.org/intellij/sdk/docs/reference_guide/api_notable/api_notable_list_2020.html#notable-changes-in-intellij-platform-20203

**Comment by hurricup** [comment]
Sorry, I'm not quite sure I understand what is your problem.
As I understand, you don't want to change `JAVA_HOME` on your machine to use jdk11. 
But you still can choose any sdk for your project and/or gradle in IDEA.

**Comment by megantracy93** [comment]
Correct, I don't want to change my JAVA_HOME. I also would rather not have to configure it in IDEA as I prefer to run gradle commands from the terminal _and_ I need to be able to build my plugin from a CI environment which uses a terminal as well. So, I need a way to configure the java version in the gradle configuration itself. I see the grammarkit plugin is [currently configured to request java 8 ](https://github.com/JetBrains/gradle-grammar-kit-plugin/blob/master/build.gradle#L23)- would it just be as simple as updating that to java 11 and releasing a new version with that?

**Comment by hurricup** [comment]
No, this only means that plugin may be used with java 8 or older. 
Your problem it's more about how to configure gradle to use different java's to run, not about this plugin.

Probably this may help you: https://stackoverflow.com/questions/18487406/how-do-i-tell-gradle-to-use-specific-jdk-version

Or google :)

**Comment by jplaisted** [comment]
You could try changing your JAVA_HOME for just that terminal that is building that project. Won't impact your entire system. Still a bit of a pain, but it works.

Add scripts in your home directory to change JAVA_HOME so you can easily switch. That's what I ended up with.
