### ISSUE TITLE
Include required libs on the task classpath

### ISSUE THREAD

**Issue by AlecStrong** [JetBrains/gradle-grammar-kit-plugin#36]
Currently the `Generate` tasks [pull their dependencies off of the compile classpath](https://github.com/JetBrains/gradle-grammar-kit-plugin/blob/master/src/main/groovy/org/jetbrains/grammarkit/tasks/GenerateParser.groovy#L28-L45), in my downstream project I [manually add maven dependencies](https://github.com/AlecStrong/sql-psi/blob/master/build.gradle#L78-L90) to the classpath of the task like this:

```groovy
  dependencies {
    maven { url 'https://www.jetbrains.com/intellij-repository/releases' }
    maven { url "https://cache-redirector.jetbrains.com/intellij-dependencies" }
  }

  configurations {
    grammar
  }

  dependencies {
    grammar "com.jetbrains.intellij.platform:indexing-impl:$ideaVersion"
    grammar "com.jetbrains.intellij.platform:analysis-impl:$ideaVersion"
    grammar "org.jetbrains.intellij.deps:asm-all:7.0.1"
  }

  tasks.withType(GenerateParser).configureEach {
    classpath = configurations.grammar + configurations.compileOnly
  }
```

Which I'm okay doing, but I wonder if there would be any interest in upstreaming this behavior now that the dependencies are all proper maven coordinates? I'd be happy to contribute such a change if it makes sense, but wanted to check in case its undesirable

**Comment by hurricup** [comment]
If I get this right, you are suggesting:

1. Introduce some `generateParser` configuration
2. Use it as additional source for dependencies

If yes, i'm totally ok with this. 

Few notes:
1. probably something more specific than `grammar`, e.g. `generateParserClassPath`  or `grammarKitClassPath`
2. dependencies collecting should be changed:
    - for each dependency (first wins)
      - look in 'generateParser' configuraion
      - look in `compileClasspath` configuration
with such approach user will be able to override ones from IntelliJ if necessary.
3. Don't forget to update README if you going to implement this.

**Comment by AlecStrong** [comment]
sounds great! I'll take a shot at it and open a PR with the proposed change

**Comment by hurricup** [comment]
Also, pls check it works with your case, as far as we lack of tests :) shame....
