### ISSUE TITLE
How to implement PsiElement.getReference?

### ISSUE THREAD

**Issue by amynbe** [JetBrains/gradle-grammar-kit-plugin#39]
Issue #23 means you can't use `psiImplUtilClass` to generate your method overrides in the PsiElement implementation.

Then how am I supposed to add support for references in my PsiElements?

Let's try to bridge the gap between https://plugins.jetbrains.com/docs/intellij/references-and-resolve.html and https://github.com/JetBrains/Grammar-Kit/blob/master/HOWTO.md:

- The former says you need to implement getReference() in your PsiElement 
- the latter talks about "III. HOWTO: Generated PSI Classes Hierarchy" but is not explicit about how to do what the former says.

I guess my underlying wish here is to improve a little bit the documentation. For a new comer to grammar kit (I've done plugin dev before but without grammar), it's hard to understand.

For example it took me a while to understand the `psiImplUtilClass` trick, i.e you implement your PsiElement interface in a static class then grammarkit will call your static helpers from within the XxxPsiElementImpl. This magic trick should be made explicit in the doc.

Another thing that in my opinion is not made clear is the difference between `extends` and `mixin`, these seem to do the same thing.

PS, I think the grammar kit doc is great in general and just need a few gaps filled to become 100% new-user-friendly.

**Comment by DemonWav** [comment]
`mixin` should do what you need in order to support references.

**Comment by amynbe** [comment]
Thank you @DemonWav, this is working.
