### ISSUE TITLE
`grammarKitRelease` option doesn't work for 2021 versions

### ISSUE THREAD

**Issue by fcurts** [JetBrains/gradle-grammar-kit-plugin#41]
Setting `grammarKitRelease` to any of the following versions works: 2019.3, 2020.1, 2020.3.1

Setting `grammarKitRelease` to any of the following versions does not work: 2020.3, 2021.1, 2021.1.1

Gradle error: "Could not find com.github.JetBrains:Grammar-Kit:2021.1.1."

id("org.jetbrains.grammarkit") version "2021.1.3"
Gradle 7.1
AdoptOpenJDK-11.0.11+9
macOS 11.4

**Comment by gregsh** [comment]
https://github.com/JetBrains/Grammar-Kit/issues/276#issuecomment-870998121

**Comment by fcurts** [comment]
@gregsh Does the fix use/require JitPack? JitPack is not an option for us (blocklisted on CI) and shouldn't be used for production grade dependencies.

**Comment by hurricup** [comment]
> @gregsh Does the fix require dependency resolution from JitPack? JitPack is not an option for us (blocklisted on CI) and shouldn't be used for production grade dependencies.

AFAIK for now GK is not published on any maven repo, so JitPack is the only easy way. But if you have your own maven repo, you may put released GK there and add it to the list of repo in your build script.

**Comment by fcurts** [comment]
@hurricup Our workaround is to put the GK JAR under source control. Would be great if GK was published to Maven Central like other Java OSS libraries.

**Comment by hurricup** [comment]
Yep, forgot to mention this way :)
True. would be nice, @gregsh

**Comment by fcurts** [comment]
filed https://github.com/JetBrains/Grammar-Kit/issues/279
