### ISSUE TITLE
Update JFlex to latest version

### ISSUE THREAD

**Issue by mathze** [JetBrains/gradle-grammar-kit-plugin#51]
I'm encountering some issues (e.g. [jflex/#216](https://github.com/jflex-de/jflex/issues/216)) while searching for this, I recognized, that the issue was already fixed.
Than I remembered about the patched jflex thing.
So I'm not quite sure if this is the right place to ask, but would it possible to get a up-to-date jflex-patch?
Also I don't know the reasons for the 'custom patched version' but maybe it's worth to check if it is still required with the latest official jflex version.

plugin-version: 2021.1.3
gradle-version: 7.2
os: Win 11

**Comment by YannCebron** [comment]
please report to https://github.com/JetBrains/intellij-deps-jflex
