### ISSUE TITLE
Could not find dev.thiagosouto:plugin:1.3.4 with `org.jetbrains.grammarkit` 2021.2.1

### ISSUE THREAD

**Issue by Undin** [JetBrains/gradle-grammar-kit-plugin#69]
In [IntelliJ Rust](https://github.com/intellij-rust/intellij-rust) plugin we have a [task](https://github.com/intellij-rust/intellij-rust/blob/0d08def3a3dd87ade9d289dc5854d6c281a2a505/build.gradle.kts#L415-L422) to resolve all gradle configurations. We use it to separate downloading of dependencies from compilation on CI.
But with `org.jetbrains.grammarkit` 2021.2.1, the task starts failing with the following message
```
Execution failed for task ':resolveDependencies'.
> Could not resolve all files for configuration ':bomConfiguration'.
   > Could not find dev.thiagosouto:plugin:1.3.4.
     Searched in the following locations:
       - https://cache-redirector.jetbrains.com/intellij-dependencies/dev/thiagosouto/plugin/1.3.4/plugin-1.3.4.pom
       - https://cache-redirector.jetbrains.com/intellij-repository/releases/dev/thiagosouto/plugin/1.3.4/plugin-1.3.4.pom
       - https://repo.maven.apache.org/maven2/dev/thiagosouto/plugin/1.3.4/plugin-1.3.4.pom
```

`gradle dependencies` task also fails to resolve `bomConfiguration`
<img src="https://user-images.githubusercontent.com/2539310/150493946-6ca4d1de-dd91-436d-943d-b96bf1c12e2d.png" width="500"/>

So, the question is: do you really need `dev.thiagosouto:plugin` plugin? And if yes, how is it supposed to be resolved?

**Comment by hsz** [comment]
Fixed with c10714c104212d147511457f6836b2f65ab276ac
