### ISSUE TITLE
Migrate to Grammar-Kit 2017.1.2

### ISSUE THREAD

**Issue by ice1000** [JetBrains/gradle-grammar-kit-plugin#8]
Grammar-Kit 2017.1.2 has been published. Please take a look.

**Comment by hurricup** [comment]
https://github.com/JetBrains/gradle-grammar-kit-plugin/commit/df8671e09b46cafc6f535f5e8f9cdaa40f196d6e

**Comment by ice1000** [comment]
Thanks!
