### ISSUE TITLE
Unable to initialize main class org.intellij.grammar.Main

### ISSUE THREAD

**Issue by denis417** [JetBrains/gradle-grammar-kit-plugin#83]
> Error: Unable to initialize main class org.intellij.grammar.Main
> Caused by: java.lang.NoClassDefFoundError:

The cause I think is a merge of `platform-impl.jar`, main jar and `3rd-party.jar` into `app.jar`

**Comment by hsz** [comment]
@takanuva15 Actually, mentioned jars are already added to the classpath of the `GenerateParserTask` in the latest available version.

https://github.com/JetBrains/gradle-grammar-kit-plugin/blob/e41ddac7ac4282293cbc5e21d0a06ce957508183/src/main/kotlin/org/jetbrains/grammarkit/GrammarKitPlugin.kt#L57-L73

Looking at your code, I assume you're currently using an outdated version. Could you please update to `2021.2.2`?

**Comment by takanuva15** [comment]
@hsz Ah ok, thanks! Seems I had missed that there was .2 feature release and I was using 2021.1.+
`id("org.jetbrains.grammarkit") version "2021.1.+"`

It's working after upgrading and changing `GenerateParser` to `GenerateParserTask`.

You can close this issue.

**Comment by hsz** [comment]
Thank you for the confirmation, @takanuva15 !
