### ISSUE TITLE
Would it make sense to make `GenerateParserTask` and `GenerateLexerTask` outputs cacheable?

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-grammar-kit-plugin#89]
**Is your feature request related to a problem? Please describe.**

In `--info` mode, Gradle reports that both tasks have caching disabled :/

**Describe the solution you'd like**

Just mark the tasks as `@CacheableTask`?

**Describe alternatives you've considered**

Currently I'm doing sth like:

```
task generateMacheteParser(type: GenerateParserTask) {
  outputs.cacheIf { true }

  // ...
}

task generateMacheteLexer(type: GenerateLexerTask) {
  outputs.cacheIf { true }

  dependsOn generateMacheteParser

  // ...
}

**Comment by PawelLipski** [comment]
Also! there's a caveat around `GenerateParserTask` `targetRoot` and `GenerateLexerTask` `targetDir`... the two folders should not be overlapping, or Gradle won't attempt to cache the outputs of either task :/ This isn't particularly obvious (and only gets reported on `--info` level in Gradle)... it would be good to mention in the docs that the generated Java sources of the tasks shouldn't go to a single directory, but instead two separate ones, like this:

![image](https://user-images.githubusercontent.com/3383210/175890107-69ae068b-9db4-4636-ac87-6d0b21f559bf.png)

See https://github.com/VirtusLab/git-machete-intellij-plugin/pull/946/files#diff-18fccbc3a3c0c8aff70a53e41afdd0cbd8b86cca800071243407fe2edf620400

**Comment by YannCebron** [comment]
I'm not sure the complexity to track all involved variables (including specific properties in .bnf/.flex files) is worth the efforts or even doable.

YMMV I enable these tasks only when actively working on lexer/parser with manual temporary `dependsOn` in Gradle. Why do you want to run them all the time?

**Comment by PawelLipski** [comment]
> YMMV I enable these tasks only when actively working on lexer/parser

Oh! so do I understand correctly that you keep the parser/lexer-generated code checked in to git and not git-ignored? 🤔

**Comment by YannCebron** [comment]
yes. I see no point in regenerating it from scratch all the time. Apart from that, not all setups are fully supported by the Gradle plugin so I *have* to generate Parser manually.

**Comment by PawelLipski** [comment]
Okay, I'll reconsider my setup then... feel free to close the issue
