### ISSUE TITLE
Gradle tasks spuriously failing when building against 2022.3 EAP due to Java 11/17 discrepancy

### ISSUE THREAD

**Issue by PawelLipski** [JetBrains/gradle-grammar-kit-plugin#97]
**Describe the bug**

```
Error: Unable to initialize main class org.intellij.grammar.Main
Caused by: java.lang.UnsupportedClassVersionError: com/intellij/lang/LanguageBraceMatching has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
Unable to initialize main class org.intellij.grammar.Main


Caused by: java.lang.UnsupportedClassVersionError: com/intellij/lang/LanguageBraceMatching has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**To reproduce**

The error is somewhat spurious in the sense that it depends on the JDK/Gradle setup on a specific machine (although if it happens on a given machine, then it happens deterministically). We don't know the exact combination of factors; killing Gradle processes and/or clearing up ~/.gradle/ seems to have helped on some machines.

Might be reproduced on [latest `develop` of git-machete-intellij-plugin](https://github.com/VirtusLab/git-machete-intellij-plugin/tree/develop)... but again, depends on a specific machine. Having `java` point to Java 11 (rather than 17) might increase the chances (although the issue was observed even with `java` pointing to Java 17).

**Additional context**

I believe this is caused by the following circumstances:
1. Since 2022.3, classes of IntelliJ (like `com/intellij/lang/LanguageBraceMatching`) are compiled for Java 17 (classfiles version 17+44=61).
2. JDK version for Java compilation can be set up in Gradle via [`java { toolchain { ... } }`](https://docs.gradle.org/current/userguide/toolchains.html#specify_custom_toolchains_for_individual_tasks); this, however, apparently does not affect the Java version used for [`execOperations.javaexec` in `GenerateLexerTask`](https://github.com/JetBrains/gradle-grammar-kit-plugin/blob/master/src/main/kotlin/org/jetbrains/grammarkit/tasks/GenerateLexerTask.kt#L92)
3. If `GenerateLexerTask`, for whatever reason, still runs under Java 11, then an attempt to load `org.intellij.grammar.Main` (itself a Java 11 class) fails since Java 11 cannot load Java 17 classes from IntelliJ 2022.3.

**Suggested remedy**

Maybe make the Java version used for `.javaexec` configurable in both `GenerateLexerTask` and `GenerateParserTask`? As suggested in [Gradle docs](https://docs.gradle.org/current/userguide/toolchains.html#specify_custom_toolchains_for_individual_tasks)

**Environment:**
 - OS: macOS
 - Gradle Grammar-Kit Plugin Version: 2021.2.2
 - Gradle Version: 7.5.1

...although as stated, it's more about IntelliJ/Java version in this case.

**CC**
@LukaszKontowski, @MaciejG604

**Comment by PawelLipski** [comment]
Delving deeper... looks that ultimately the JVM to run is selected inside `org.gradle.process.internal.DefaultExecActionFactory.DecoratingExecActionFactory#newDecoratedJavaExecAction` (at least under Gradle 7.4.2), which in turn uses:

```java
        public JavaExecAction newDecoratedJavaExecAction() {
            final JavaForkOptionsInternal forkOptions = newDecoratedJavaForkOptions();
            forkOptions.setExecutable(Jvm.current().getJavaExecutable());
            return instantiator.newInstance(
                DefaultJavaExecAction.class,
                fileResolver,
                fileCollectionFactory,
                objectFactory,
                executor,
                buildCancellationToken,
                temporaryFileProvider,
                javaModuleDetector,
                forkOptions
            );
        }
```

So just `Jvm.current()`, not really configurable apparently ☹️

**Comment by PawelLipski** [comment]
For a 100% reproducible setup:

```shell
 docker run gitmachete/intellij-plugin-ci:9.0.0 'git clone https://github.com/VirtusLab/git-machete-intellij-plugin --depth=1 --branch=debug/grammar-kit-java-17 gmip/ && cd gmip && ./gradlew frontend:file:generateLexer'
```

Basically, this runs in a container where Java 11 is installed by default.

**Comment by PawelLipski** [comment]
Let @MaciejG604 take a look (rewrite both tasks to `JavaExec`)

**Comment by hsz** [comment]
Thanks for raising this issue, Paweł – I agree that making tasks exec-like is a good move.
